(G-Code file generated by CNCWeld)
$H (Home before anything)
G0 F300 X1.70043 Y110.11 Z-43 (Go to first point quickly)
M3 (Switch on the torch)
G01 F300 X5.27108 Y110.185 Z-43
G01 F300 X6.71676 Y109.915 Z-43
G01 F300 X6.72358 Y109.815 Z-43
G01 F300 X472.059 Y77.545 Z-43
G01 F300 X472.062 Y77.445 Z-43
M5 (Switch off the torch)
G0 Z0 (Raise the torch from the workpiece quickly)
G0x0y0z0 (Go back home, done)